conky.config = {
    background = false,
    alignment = 'top_left',
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:bold:size=9',
    gap_x = 1369,
    gap_y = 3,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = yes,
    out_to_x = no,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'panel',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager,above',
    own_window_colour = "100032",
    show_graph_range = false,
    show_graph_scale = true,
    stippled_borders = 0,
    border_inner_margin = 10,
    update_interval = 0.05,   
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
	override_utf8_locale = true,
    text_buffer_size = 32768,
	imlib_cache_size = 0,
    border_outer_margin = 0,
	use_xft = true,
	xftalpha = 0.8,
}

conky.text = [[
${voffset -15}
${goto 15}${voffset 1}CPU: ${goto 51}${voffset -1}${cpugraph cpu0 30,96 7fff00 ff0000 -t} ${goto 195}${voffset -25}${color gold}Load Avg:
${goto 195}${voffset 10}${color #33FFA5}${loadavg}
${voffset -15}
]]