#!/bin/bash
source $(pwd)/variables

ohmyzsh() {
    rm -rf $HOME/.oh-my-zsh
    cd $REPO_DIR/data_prepared
    declare -a gitarray
    gitarray=('zsh-users/zsh-syntax-highlighting.git '$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'' 'zsh-users/zsh-autosuggestions '$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions'' 'spaceship-prompt/spaceship-prompt.git '$HOME/.oh-my-zsh/custom/themes/spaceship-prompt'' 'TamCore/autoupdate-oh-my-zsh-plugins '$HOME/.oh-my-zsh/custom/plugins/autoupdate'')
    sh install.sh --unattended
    for i in "${gitarray[@]}"; do
        echo $(git clone https://github.com/$i)
    done
    ln -s $HOME/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme $HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    rm -rf $HOME/.oh-my-zsh/themes
}

terminal() {
    id=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
    profile_path="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$id/"
    keybindings_path="org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/"
    keybindings=("copy '<Ctrl>C'" "new-tab '<Ctrl>T'" "new-window '<Ctrl>N'" "save-contents '<Ctrl>S'" "close-tab '<Ctrl>W'" "close-window '<Ctrl>Q'" "copy-html '<Ctrl>X'" "paste '<Ctrl>V'" "select-all '<Ctrl>A'" "preferences '<Ctrl>P'" "find '<Ctrl>F'" "find-next '<Ctrl>G'" "find-previous '<Ctrl>H'" "find-clear '<Ctrl>J'")
    profile=("visible-name '$user_current'" "cursor-shape 'ibeam'")
    for binding in "${keybindings[@]}"; do
        gsettings set $keybindings_path $binding
    done
    for setting in "${profile[@]}"; do
        gsettings set $profile_path $setting
    done
    gsettings set org.gnome.desktop.interface enable-hot-corners false
    cd $REPO_DIR/data_prepared/gnome-terminal
    ./install.sh -s Dracula -p $user_current --skip-dircolors
    cd $REPO_DIR/create_users
    if [ -f $HOME/.zshrc ]; then
        rm -rf $HOME/.zshrc
    fi
    cp .zshrc $HOME/.zshrc
    cp .spaceshiprc.zsh $HOME/.spaceshiprc.zsh
}

accessibility() {
    interface_settings=(
        "text-scaling-factor 1.25"
        "gtk-theme 'red_hat_linux_themes'"
        "icon-theme 'rhel'"
        "cursor-theme 'WhiteSur-cursors'"
        "clock-show-date true"
        "show-battery-percentage true"
        "clock-show-seconds true"
        "clock-show-weekday true"
    )
    for setting in "${interface_settings[@]}"; do
        gsettings set org.gnome.desktop.interface $setting
    done
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
    gsettings set org.gnome.desktop.session idle-delay 1800
    gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
    gsettings set org.gnome.desktop.input-sources show-all-sources true
    gsettings set org.gnome.desktop.input-sources sources "[('ibus', 'm17n:vi:telex'), ('xkb', 'us')]"
    gsettings set org.gnome.desktop.interface locate-pointer true
    gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'
}

gnome_extensions() {
    cd $REPO_DIR/data_prepared
    declare -a extensions
    extensions=('3628' '4679' '1082' '3088' '1486' '3843' '120' '3733' '5219' '1460' '4670' '1160')
    for i in "${extensions[@]}"; do
        echo $(./install-gnome-extensions.sh -o -u $i)
    done
    sed -i "s/Main.panel.addToStatusArea ('cpufreq-indicator', monitor);/Main.panel.addToStatusArea ('cpufreq-indicator', monitor, 0, 'center');/g" $HOME/.local/share/gnome-shell/extensions/cpufreq@konkor/extension.js
    sed -i "s/Main.panel.addToStatusArea(Me.metadata.uuid, this._button, 0, 'right')/Main.panel.addToStatusArea(Me.metadata.uuid, this._button, 1, 'right')/g" $HOME/.local/share/gnome-shell/extensions/extension-list@tu.berry/extension.js
    sed -i "s/panel.addToStatusArea('extensions-sync', this.button);/panel.addToStatusArea('extensions-sync', this.button, '2', 'right');/g" $HOME/.local/share/gnome-shell/extensions/extensions-sync@elhan.io/extension.js
    sed -i "s/panel = Main.panel._rightBox;/panel = Main.panel._leftBox;/g" $HOME/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js
    sed -i "s/var UPDATE_INTERVAL_CPU = 2000;/var UPDATE_INTERVAL_CPU = 100;/g" $HOME/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/lib/config.js
}

keybinding() {
    KEY0_PATH="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
    KEY_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings \
        "['$KEY_PATH/custom0/']"
    gsettings set $KEY0_PATH:$KEY_PATH/custom0/ name "GNOME Terminal"
    gsettings set $KEY0_PATH:$KEY_PATH/custom0/ command "gnome-terminal"
    gsettings set $KEY0_PATH:$KEY_PATH/custom0/ binding "<Primary><Alt>T"
}

tasks=("ohmyzsh" "terminal" "accessibility" "gnome_extensions" "keybinding")
for task in "${tasks[@]}"; do
    check_and_run "$task"
done
