#!/bin/bash
REPO_DIR="$(dirname "$(readlink -m "${0}")")"








cd $REPO_DIR
sudo sh super_user $USER


git-credential-manager configure
git config --global credential.credentialStore secretservice
