# USER
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=green
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR=yellow
SPACESHIP_USER_PREFIX="owner user "
SPACESHIP_TIME_FORMAT='%D{%A %B %d/%m/%Y %H:%M:%S}'
