#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Fedora Linux LUKS2 (os_version)" --class (os_name) {
	search --no-floppy --fs-uuid --set=root (boot_uuid)
	chainloader /linux_uki_based_redhat.efi
	boot
}
