#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Red Hat Enterprise Linux (os_version) EncryptLUKS2" --class (os_name) {
	search --no-floppy --fs-uuid --set=first (efi_uuid)
	tpm2_key_protector_init -T ($first)/efi/seal.tpm
	cryptomount -u (boot_uuid) -P tpm2
	search --no-floppy --fs-uuid --set=root (boot_mapper_uuid)
	linux /vmlinuz-(kernel_version) crashkernel=512M rhgb (kernel_parameters)
	initrd /initramfs-(kernel_version).img
}
