#!/usr/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Red Hat Enterprise Linux (os_version) EncryptLUKS2" --class (os_name) {
	search --no-floppy --fs-uuid --set=root (boot_mapper_uuid)
	linux /vmlinuz-(kernel_version) crashkernel=512M lockdown=confidentiality rd.shell=0 rhgb (kernel_parameters)
	initrd /initramfs-(kernel_version).img
}
