# USER
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR_ROOT=red
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D{%A %d/%m/%Y %H:%M:%S}'
SPACESHIP_SUDO_SHOW=true
SPACESHIP_TIME_COLOR=green
SPACESHIP_SUDO_SYMBOL="//ROOT/SUDO"
