# USER
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=green
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D{%d/%m/%y %A %H:%M:%S}'
SPACESHIP_TIME_COLOR=yellow
SPACESHIP_USER_PREFIX="owner "
SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
