#!/bin/bash
# You may want to do this if your code is in a script.
unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT

# Hide the cursor (there is probably a much better way to do this)
printf '\e[?25l'
clear 
while true ; do
    # Move the cursor to the top of the screen but don't clear the screen
    printf '\033[;H' 
    	a=$(lscpu | grep 'CPU MHz' | awk '{print $3}')
    	COUNT=0
	SUM=0
	
	for VAL in `find /sys/devices/system/cpu -name scaling_cur_freq -exec cat {} \;`; do
		COUNT=$((${COUNT}+1))
		SUM=$((${SUM}+${VAL}))
	done
	
	if [ ${COUNT} -eq 0 -o ${SUM} -eq 0 ]; then
		/bin/echo -n "no cpufreq"
		exit 1
	fi

	FREQ=`echo ${SUM} ${COUNT} | awk '{ printf "%.1f", $1 / 1000000 / $2; }'`

	/bin/echo -n "CPU: ${FREQ} GHz " "CPU MHz: $a"
    	sleep 1
done