#!/bin/bash
source $(pwd)/variables
rm -rf logs
[ ! -d $HOME/Prj ] && mkdir -p $HOME/Prj
mkdir -p $REPO_DIR/logs
cd $REPO_DIR
sudo sh super_user
sh normal_user
sudo dnf remove jq -y
sudo dnf autoremove -y
